---
kind: pipeline
type: docker
name: default

steps:
  - name: binaries
    image: goreleaser/goreleaser
    pull: if-not-exists
    commands:
      - cd backend
      - goreleaser build --snapshot --rm-dist

  - name: ui-build
    image: kameshsampath/drone-ci-extension-ui-base
    pull: if-not-exists
    environment:
      # this is required by Docker Extension to load
      # static files from extension path on the Host
      PUBLIC_URL: .
      BROWSER: none
      CI: false
    commands:
      - cd ui
      - pnpm install
      - pnpm run clean && pnpm run build

  - name: build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    pull: if-not-exists
    settings:
      dry_run: true
      output: "type=docker"
      daemon_off: true
      dockerfile: docker/Dockerfile.standalone
      cache_from:
        - 'type=registry\\,ref=kameshsampath/drone-ci-docker-extension-cache'
      cache_to: "type=registry,ref=kameshsampath/drone-ci-docker-extension-cache"
      repo: drone/drone-ci-docker-extension
      tag:
        - latest
      # keep the core context to minimum as we load named contexts
      context: docker
      named_context:
        - dist=backend/dist
        - ui=ui/build
        - scripts=backend/scripts
        - etc=etc
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: cleanup
    image: kameshsampath/kube-dev-tools:0.0.8
    privileged: true
    commands:
      - >
        docker ps --filter=ancestor="moby/buildkit:buildx-stable-1" --format="{{ .ID }}" | xargs docker rm --force
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

volumes:
 - name: dockersock
   host:
     path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: build-base

steps:
  - name: build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      daemon_off: true
      dockerfile: docker/Dockerfile.pnpm
      repo: kameshsampath/drone-ci-extension-ui-base
      cache_from:
        - 'type=registry\\,ref=kameshsampath/docker-extension-ui-cache'
      cache_to: "type=registry,ref=kameshsampath/docker-extension-ui-cache"
      tag:
        - latest
      platforms:
        - linux/amd64
        - linux/arm64
      context: ui
